import { financeLiteracyImg, financeLiteracyImg2, financeLiteracyImg3, financeLiteracyImg4, financeLiteracyImg5, generatorsImg, generatorsImg2, gptImg, gptImg2, gptImg3, linkerImg, quizImg, quizImg2, quizImg3 } from "../../assets/thumbnails";
import { technologies } from "../../pages/Experience/technologies";

const getUsedTech = (type: string, techs: string[]) => {
  const frontendTechnologies = technologies[0].technologies;
  const backendTechnologies = technologies[1].technologies;
  const gameDevTechnologies = technologies[2].technologies;
  const usedTech = [];

  const allTechnologies = type === "web" ? frontendTechnologies.concat(backendTechnologies) : gameDevTechnologies;

  for (let i = 0; i < techs.length; i++) {
    const addTech = allTechnologies.find((item) => item.title === techs[i]);
    usedTech.push(addTech);
  }
  return usedTech as { img: string; title: string; labels: string[] }[];
};

export const projects = [
  {
    type: "web",
    projects: [
      {
        title: "OpenAI Chat & Images",
        path: "gpt",
        usedTechImgs: getUsedTech("web", ["Next JS", "Typescript", "React Query", "Tailwind", "Mongo DB", "Prisma ORM", "Docker"]),
        description: `Introducing my innovative Next.js-powered app that seamlessly blends cutting-edge technology with user-friendly features. This app is a powerhouse for image generation using AI, allowing users to effortlessly create captivating visuals with just a few clicks. Beyond image creation, users can engage in dynamic conversations with our AI chatbot, offering a personalized and interactive experience.\n\nBut that's not all – I take exploration to a new level by offering city-based tours generated by AI. Simply input your desired city, and let our app curate a unique and personalized tour experience for you. Whether you're a local or a traveler, our AI-powered tours promise to unveil hidden gems and popular attractions alike.\n\nLooking ahead, I have exciting plans to implement a secure payment system, enabling users to purchase tokens. These tokens will unlock premium features, allowing users to generate a variety of content and experiences within the app. Join me on this journey as I'll continue to evolve and enhance the capabilities of app, bringing the future of AI-driven creativity and exploration to your fingertips.`,
        img: [gptImg, gptImg2, gptImg3],
        video: "",
        liveSiteURL: "https://gpt.bwrd.eu",
        demoSiteURL: "",
        availableForPublic: true,
        inDevelopment: false
      },
      {
        title: "Finance Literacy Game",
        path: "finance-literacy",
        usedTechImgs: getUsedTech("web", ["React JS", "Typescript", "React Query", "SASS", "Mongo DB", "Docker", "Google Cloud"]),
        description:
          "The game is meticulously designed to provide players with an interactive and immersive experience centered around effectively managing their finances. Through a series of engaging life-based scenarios, players are presented with a variety of financial challenges, each aimed at honing their decision-making skills in the realm of personal finance. This approach not only adds a dynamic and practical dimension to the gaming experience but also serves as a valuable educational tool, empowering players to make informed and strategic financial choices.\n\nIn addition to the thought-provoking scenarios, the game goes the extra mile by offering detailed charts and data visualizations. These visual aids serve as powerful tools, delivering a comprehensive overview of players' financial progress within the game. By presenting information in a visually accessible manner, the game fosters a deeper understanding of financial dynamics and allows players to track their advancements and setbacks with clarity. This feature contributes to the overall richness of the gaming experience, providing players with valuable insights into their virtual financial journeys.",
        img: [financeLiteracyImg, financeLiteracyImg2, financeLiteracyImg3, financeLiteracyImg4, financeLiteracyImg5],
        video: "",
        liveSiteURL: "https://fmk.bwrd.eu",
        demoSiteURL: "",
        availableForPublic: true,
        inDevelopment: true
      },
      {
        title: "QR & Quiz App",
        path: "quiz-app",
        usedTechImgs: getUsedTech("web", ["React JS", "Typescript", "React Query", "SASS"]),
        description:
          "Created an engaging mobile-centric quiz app for cities Puchov and Uherske Hradiste as a solo frontend developer. This cutting-edge app, meticulously developed based on the provided UX design, serves as a dynamic platform that seamlessly integrates technology with the exploration of our cities' scenic parks.\n\nThe diversity of question types within the quiz adds another layer of depth to the user experience. From multiple-choice queries to picture-based challenges, the app ensures that users encounter a variety of interactive elements that cater to different preferences and learning styles.\n\nIn tandem with the user-facing features, the project also incorporated a streamlined administrative system.\n\nWe have not only created an engaging quiz application but also contributed to the promotion of local community interaction and knowledge dissemination. This project exemplifies our dedication to leveraging technology for the betterment of our communities and enhancing the overall quality of life for our residents.",
        img: [quizImg, quizImg2, quizImg3],
        video: "",
        liveSiteURL: "https://kvizovahra.sk/",
        demoSiteURL: "",
        availableForPublic: true,
        inDevelopment: false
      },
      {
        title: "Random Generators",
        path: "generators",
        usedTechImgs: getUsedTech("web", ["React JS", "Typescript", "React Query", "CSS"]),
        description:
          "Made specifically for the company I work for as a software tester, this comprehensive generator tool simplifies our daily tasks. It allows for customizable Lorem Ipsum text generation with adjustable paragraph and character counts, and the creation of random birth numbers for both mens and womens. The project also incorporates a straightforward daily report list feature.",
        img: [generatorsImg, generatorsImg2],
        video: "",
        liveSiteURL: "https://bwrd.eu/#/tipsport",
        demoSiteURL: "",
        availableForPublic: true,
        inDevelopment: false
      },
      {
        title: "Linker App",
        path: "linker-app",
        usedTechImgs: getUsedTech("web", ["Javascript", "HTML", "CSS"]),
        description:
          "Crafted during my time as a customer technical support representative, this project aimed to streamline our diagnostic processes by consolidating various tools into one simple linking application. It also featured an organized collection of manuals and essential resources, neatly sorted into relevant categories for quick and easy access.",
        img: [linkerImg],
        video: "",
        liveSiteURL: "",
        demoSiteURL: "",
        availableForPublic: false,
        inDevelopment: false
      },
    ],
  },
  {
    type: "gamedev",
    projects: [
      {
        title: "5 Nights To Live",
        path: "5-nights-to-live",
        usedTechImgs: getUsedTech("gamedev", ["Unreal Engine"]),
        description:
          "Immerse yourself in a thrilling adventure. '5 Nights To Live' is a heart-pounding first-person shooter game that thrusts players into a dense, foreboding forest. Battle for survival as you confront nightly onslaughts of relentless zombies, putting your skills and wits to the ultimate test.",
        img: [""],
        video: "https://www.youtube.com/embed/CY64diSC2Rg?si=PUTQkDd9IMhzKCcr",
        liveSiteURL: "",
        demoSiteURL: "https://roman-bwoody-durek.itch.io/5-nights-to-live",
        availableForPublic: true,
        inDevelopment: false
      },
      {
        title: "Crystal Hunter",
        path: "crystal-hunter",
        usedTechImgs: getUsedTech("gamedev", ["Unreal Engine"]),
        description:
          "Crafted during the TEDI Game Jam #25, 'Crystal Hunter' is a thrilling adventure game that runs on the powerful Unreal Engine 5. Embark on an exciting journey to collect precious crystals while navigating through immersive levels filled with challenging obstacles. Can you conquer the game and emerge as the ultimate Crystal Hunter?",
        img: [""],
        video: "https://www.youtube.com/embed/_4y_Be1iaKQ?si=HlgySpobo_fVqPpx",
        liveSiteURL: "",
        demoSiteURL: "https://roman-bwoody-durek.itch.io/crystal-hunter",
        availableForPublic: true,
        inDevelopment: false
      },
      {
        title: "Pirate Dodge",
        path: "pirate-dodge",
        usedTechImgs: getUsedTech("gamedev", ["Godot"]),
        description:
          "Utilizing the versatile Godot game engine, I crafted a thrilling 2D hyper-casual single-player experience, marking my maiden venture into game development. In this adrenaline-packed adventure, players must deftly evade a relentless barrage of cannonballs, striving to survive the onslaught for as long as possible. ",
        img: [""],
        video: "https://www.youtube.com/embed/ef8uVD6Uq-k?si=X9pyGCJx3GOegxFL",
        liveSiteURL: "",
        demoSiteURL: "",
        availableForPublic: true,
        inDevelopment: false
      },
    ],
  },
];
